// data/projects.ts
export const PROJECTS = [
    {
        id: 1,
        title: "AI Research Platform",
        description: "AI-driven research automation platform that leverages machine learning to streamline complex research workflows. Enables teams to collaborate efficiently and extract insights from large datasets with minimal manual intervention.",
        summary: "Automated research platform powered by AI",
        images: ["/projects/p1.png", "/projects/p1-alt.png"],
        tech: ["AI", "Next.js", "Python"],
        link: "https://example.com",
    },
    {
        id: 2,
        title: "SaaS Analytics",
        description: "Real-time analytics dashboard that provides comprehensive business intelligence and performance metrics. Track user behavior, conversion funnels, and revenue metrics with interactive visualizations and custom reporting.",
        summary: "Real-time business analytics dashboard",
        images: ["/projects/p2.png", "/projects/p2-alt.png"],
        tech: ["React", "Node", "Postgres"],
        link: "https://example.com",
    },
    {
        id: 3,
        title: "AI Agent System",
        description: "Autonomous AI agents architecture designed for multi-task orchestration and intelligent decision-making. Supports complex workflows with memory management, tool integration, and inter-agent communication.",
        summary: "Autonomous AI agent framework",
        images: ["/projects/p3.png", "/projects/p3-alt.png"],
        tech: ["LangChain", "OpenAI"],
        link: "https://example.com",
    },
    {
        id: 4,
        title: "FinTech Platform",
        description: "Secure finance dashboard with bank-grade encryption and compliance standards. Manage transactions, investments, and financial planning with real-time market data integration and portfolio tracking.",
        summary: "Enterprise-grade fintech solution",
        images: ["/projects/p4.png", "/projects/p4-alt.png"],
        tech: ["Next.js", "Stripe"],
        link: "https://example.com",
    },
    {
        id: 5,
        title: "ML Ops Pipeline",
        description: "Model deployment automation system that streamlines the lifecycle from training to production. Includes monitoring, versioning, and rollback capabilities for seamless ML model management across environments.",
        summary: "Automated ML model deployment system",
        images: ["/projects/p5.png", "/projects/p5-alt.png"],
        tech: ["ML", "Docker"],
        link: "https://example.com",
    },
    {
        id: 6,
        title: "Portfolio Engine",
        description: "High-performance portfolio site with stunning 3D animations and smooth scrolling interactions. Built for speed and visual appeal with advanced GPU-accelerated graphics and optimized rendering.",
        summary: "Interactive 3D portfolio website",
        images: ["/projects/p6.png", "/projects/p6-alt.png"],
        tech: ["Three.js", "GSAP"],
        link: "https://example.com",
    },
];
